{{- $name := $.Values.name -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
spec:
  type: {{ $.Values.service.type }}
  selector:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ $.Values.port }}
      protocol: TCP
      targetPort: 8080
